# Generated by Django 5.1 on 2024-08-24 08:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('main', '0002_linkmapping_delete_question'),
    ]

    operations = [
        migrations.AlterField(
            model_name='linkmapping',
            name='original_url',
            field=models.TextField(),
        ),
    ]
